// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package net.btcpc.uniffi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_btcpc_mobile_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_btcpc_mobile_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_btcpc_mobile_core"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}


















































































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "btcpc_mobile_core")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
    }

    fun uniffi_btcpc_mobile_core_fn_func_derive_all_pubkeys(`mnemonicWords`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_derive_posting_pubkey(`mnemonicWords`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_fetch_account(`baseUrl`: RustBuffer.ByValue,`account`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_fetch_balance(`baseUrl`: RustBuffer.ByValue,`account`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_fetch_inference_jobs(`baseUrl`: RustBuffer.ByValue,`statusFilter`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_fetch_node_info(`baseUrl`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_parse_ble_frame(`rawFrame`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_post_account_create(`baseUrl`: RustBuffer.ByValue,`account`: RustBuffer.ByValue,`keysJson`: RustBuffer.ByValue,`fundedBy`: RustBuffer.ByValue,`sigHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_post_coverage_report(`baseUrl`: RustBuffer.ByValue,`reporter`: RustBuffer.ByValue,`lat`: Double,`lon`: Double,`signalDbm`: RustBuffer.ByValue,`carrierMccMnc`: RustBuffer.ByValue,`technology`: RustBuffer.ByValue,`dataHash`: RustBuffer.ByValue,`sigHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_post_inference_bid(`baseUrl`: RustBuffer.ByValue,`jobId`: RustBuffer.ByValue,`bidder`: RustBuffer.ByValue,`fee`: Long,`role`: RustBuffer.ByValue,`nonce`: Long,`sigHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_post_inference_complete(`baseUrl`: RustBuffer.ByValue,`jobId`: RustBuffer.ByValue,`worker`: RustBuffer.ByValue,`resultHash`: RustBuffer.ByValue,`latencyMs`: Long,`outputText`: RustBuffer.ByValue,`sigHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_post_node_capability(`baseUrl`: RustBuffer.ByValue,`account`: RustBuffer.ByValue,`sigHex`: RustBuffer.ByValue,`epoch`: Long,`vision`: Byte,`audio`: Byte,`codeExec`: Byte,`tier`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_post_sensor_commit(`baseUrl`: RustBuffer.ByValue,`sensorId`: RustBuffer.ByValue,`owner`: RustBuffer.ByValue,`batchHash`: RustBuffer.ByValue,`readingCount`: Long,`sensorType`: RustBuffer.ByValue,`value`: RustBuffer.ByValue,`sigHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_post_sensor_register(`baseUrl`: RustBuffer.ByValue,`sensorId`: RustBuffer.ByValue,`owner`: RustBuffer.ByValue,`sensorType`: RustBuffer.ByValue,`location`: RustBuffer.ByValue,`sigHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_post_stake(`baseUrl`: RustBuffer.ByValue,`account`: RustBuffer.ByValue,`amount`: Long,`nonce`: Long,`signedBy`: RustBuffer.ByValue,`sigHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_post_transfer(`baseUrl`: RustBuffer.ByValue,`from`: RustBuffer.ByValue,`to`: RustBuffer.ByValue,`amount`: Long,`token`: RustBuffer.ByValue,`memo`: RustBuffer.ByValue,`signedBy`: RustBuffer.ByValue,`nonce`: Long,`sigHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_post_unstake(`baseUrl`: RustBuffer.ByValue,`account`: RustBuffer.ByValue,`amount`: Long,`nonce`: Long,`signedBy`: RustBuffer.ByValue,`sigHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_sign_account_create(`mnemonicWords`: RustBuffer.ByValue,`chainId`: RustBuffer.ByValue,`account`: RustBuffer.ByValue,`keysJson`: RustBuffer.ByValue,`fundedBy`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_sign_coverage_report(`mnemonicWords`: RustBuffer.ByValue,`chainId`: RustBuffer.ByValue,`reporter`: RustBuffer.ByValue,`lat`: Double,`lon`: Double,`carrierMccMnc`: RustBuffer.ByValue,`dataHash`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_sign_inference_bid(`mnemonicWords`: RustBuffer.ByValue,`chainId`: RustBuffer.ByValue,`bidder`: RustBuffer.ByValue,`jobId`: RustBuffer.ByValue,`fee`: Long,`role`: RustBuffer.ByValue,`nonce`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_sign_inference_complete(`mnemonicWords`: RustBuffer.ByValue,`chainId`: RustBuffer.ByValue,`worker`: RustBuffer.ByValue,`jobId`: RustBuffer.ByValue,`resultHash`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_sign_node_capability(`mnemonicWords`: RustBuffer.ByValue,`account`: RustBuffer.ByValue,`epoch`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_sign_sensor_commit(`mnemonicWords`: RustBuffer.ByValue,`chainId`: RustBuffer.ByValue,`sensorId`: RustBuffer.ByValue,`owner`: RustBuffer.ByValue,`batchHash`: RustBuffer.ByValue,`readingCount`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_sign_stake(`mnemonicWords`: RustBuffer.ByValue,`chainId`: RustBuffer.ByValue,`account`: RustBuffer.ByValue,`amount`: Long,`nonce`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_sign_transfer(`mnemonicWords`: RustBuffer.ByValue,`chainId`: RustBuffer.ByValue,`fromAccount`: RustBuffer.ByValue,`toAccount`: RustBuffer.ByValue,`amount`: Long,`token`: RustBuffer.ByValue,`nonce`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_sign_unstake(`mnemonicWords`: RustBuffer.ByValue,`chainId`: RustBuffer.ByValue,`account`: RustBuffer.ByValue,`amount`: Long,`nonce`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_sign_with_role(`mnemonicWords`: RustBuffer.ByValue,`chainId`: RustBuffer.ByValue,`roleIndex`: Int,`canonicalJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_btcpc_mobile_core_fn_func_verify_ble_frame_sig(`rawFrame`: RustBuffer.ByValue,`flipperPubkeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_btcpc_mobile_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_btcpc_mobile_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_btcpc_mobile_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_btcpc_mobile_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_btcpc_mobile_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_btcpc_mobile_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_btcpc_mobile_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_btcpc_mobile_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_btcpc_mobile_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_btcpc_mobile_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_btcpc_mobile_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_btcpc_mobile_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_btcpc_mobile_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_btcpc_mobile_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_btcpc_mobile_core_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_btcpc_mobile_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_btcpc_mobile_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_btcpc_mobile_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_btcpc_mobile_core_checksum_func_derive_all_pubkeys(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_derive_posting_pubkey(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_fetch_account(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_fetch_balance(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_fetch_inference_jobs(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_fetch_node_info(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_parse_ble_frame(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_post_account_create(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_post_coverage_report(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_post_inference_bid(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_post_inference_complete(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_post_node_capability(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_post_sensor_commit(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_post_sensor_register(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_post_stake(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_post_transfer(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_post_unstake(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_sign_account_create(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_sign_coverage_report(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_sign_inference_bid(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_sign_inference_complete(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_sign_node_capability(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_sign_sensor_commit(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_sign_stake(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_sign_transfer(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_sign_unstake(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_sign_with_role(
    ): Short
    fun uniffi_btcpc_mobile_core_checksum_func_verify_ble_frame_sig(
    ): Short
    fun ffi_btcpc_mobile_core_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_btcpc_mobile_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_btcpc_mobile_core_checksum_func_derive_all_pubkeys() != 12869.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_derive_posting_pubkey() != 53129.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_fetch_account() != 6784.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_fetch_balance() != 52139.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_fetch_inference_jobs() != 52282.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_fetch_node_info() != 51723.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_parse_ble_frame() != 28386.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_post_account_create() != 30884.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_post_coverage_report() != 41164.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_post_inference_bid() != 23459.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_post_inference_complete() != 61606.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_post_node_capability() != 46841.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_post_sensor_commit() != 27450.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_post_sensor_register() != 50914.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_post_stake() != 21435.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_post_transfer() != 58055.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_post_unstake() != 4220.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_sign_account_create() != 774.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_sign_coverage_report() != 50029.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_sign_inference_bid() != 389.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_sign_inference_complete() != 23638.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_sign_node_capability() != 59125.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_sign_sensor_commit() != 63549.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_sign_stake() != 21655.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_sign_transfer() != 51183.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_sign_unstake() != 42942.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_sign_with_role() != 15612.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_btcpc_mobile_core_checksum_func_verify_ble_frame_sig() != 6011.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1UL

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterInt: FfiConverter<Int, Int> {
    override fun lift(value: Int): Int {
        return value
    }

    override fun read(buf: ByteBuffer): Int {
        return buf.getInt()
    }

    override fun lower(value: Int): Int {
        return value
    }

    override fun allocationSize(value: Int) = 4UL

    override fun write(value: Int, buf: ByteBuffer) {
        buf.putInt(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



data class BleFrame (
    var `msgType`: kotlin.UByte, 
    var `payload`: kotlin.ByteArray
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBleFrame: FfiConverterRustBuffer<BleFrame> {
    override fun read(buf: ByteBuffer): BleFrame {
        return BleFrame(
            FfiConverterUByte.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: BleFrame) = (
            FfiConverterUByte.allocationSize(value.`msgType`) +
            FfiConverterByteArray.allocationSize(value.`payload`)
    )

    override fun write(value: BleFrame, buf: ByteBuffer) {
            FfiConverterUByte.write(value.`msgType`, buf)
            FfiConverterByteArray.write(value.`payload`, buf)
    }
}





sealed class MobileCoreException(message: String): kotlin.Exception(message) {
        
        class InvalidMnemonic(message: String) : MobileCoreException(message)
        
        class DerivationException(message: String) : MobileCoreException(message)
        
        class SigningException(message: String) : MobileCoreException(message)
        
        class NetworkException(message: String) : MobileCoreException(message)
        
        class ParseException(message: String) : MobileCoreException(message)
        
        class InvalidFrame(message: String) : MobileCoreException(message)
        
        class SignatureInvalid(message: String) : MobileCoreException(message)
        

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<MobileCoreException> {
        override fun lift(error_buf: RustBuffer.ByValue): MobileCoreException = FfiConverterTypeMobileCoreError.lift(error_buf)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeMobileCoreError : FfiConverterRustBuffer<MobileCoreException> {
    override fun read(buf: ByteBuffer): MobileCoreException {
        
            return when(buf.getInt()) {
            1 -> MobileCoreException.InvalidMnemonic(FfiConverterString.read(buf))
            2 -> MobileCoreException.DerivationException(FfiConverterString.read(buf))
            3 -> MobileCoreException.SigningException(FfiConverterString.read(buf))
            4 -> MobileCoreException.NetworkException(FfiConverterString.read(buf))
            5 -> MobileCoreException.ParseException(FfiConverterString.read(buf))
            6 -> MobileCoreException.InvalidFrame(FfiConverterString.read(buf))
            7 -> MobileCoreException.SignatureInvalid(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: MobileCoreException): ULong {
        return 4UL
    }

    override fun write(value: MobileCoreException, buf: ByteBuffer) {
        when(value) {
            is MobileCoreException.InvalidMnemonic -> {
                buf.putInt(1)
                Unit
            }
            is MobileCoreException.DerivationException -> {
                buf.putInt(2)
                Unit
            }
            is MobileCoreException.SigningException -> {
                buf.putInt(3)
                Unit
            }
            is MobileCoreException.NetworkException -> {
                buf.putInt(4)
                Unit
            }
            is MobileCoreException.ParseException -> {
                buf.putInt(5)
                Unit
            }
            is MobileCoreException.InvalidFrame -> {
                buf.putInt(6)
                Unit
            }
            is MobileCoreException.SignatureInvalid -> {
                buf.putInt(7)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalInt: FfiConverterRustBuffer<kotlin.Int?> {
    override fun read(buf: ByteBuffer): kotlin.Int? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterInt.read(buf)
    }

    override fun allocationSize(value: kotlin.Int?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterInt.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Int?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterInt.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalDouble: FfiConverterRustBuffer<kotlin.Double?> {
    override fun read(buf: ByteBuffer): kotlin.Double? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterDouble.read(buf)
    }

    override fun allocationSize(value: kotlin.Double?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterDouble.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Double?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterDouble.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}
    @Throws(MobileCoreException::class) fun `deriveAllPubkeys`(`mnemonicWords`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_derive_all_pubkeys(
        FfiConverterString.lower(`mnemonicWords`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `derivePostingPubkey`(`mnemonicWords`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_derive_posting_pubkey(
        FfiConverterString.lower(`mnemonicWords`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `fetchAccount`(`baseUrl`: kotlin.String, `account`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_fetch_account(
        FfiConverterString.lower(`baseUrl`),FfiConverterString.lower(`account`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `fetchBalance`(`baseUrl`: kotlin.String, `account`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_fetch_balance(
        FfiConverterString.lower(`baseUrl`),FfiConverterString.lower(`account`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `fetchInferenceJobs`(`baseUrl`: kotlin.String, `statusFilter`: kotlin.String?): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_fetch_inference_jobs(
        FfiConverterString.lower(`baseUrl`),FfiConverterOptionalString.lower(`statusFilter`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `fetchNodeInfo`(`baseUrl`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_fetch_node_info(
        FfiConverterString.lower(`baseUrl`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `parseBleFrame`(`rawFrame`: kotlin.ByteArray): BleFrame {
            return FfiConverterTypeBleFrame.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_parse_ble_frame(
        FfiConverterByteArray.lower(`rawFrame`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `postAccountCreate`(`baseUrl`: kotlin.String, `account`: kotlin.String, `keysJson`: kotlin.String, `fundedBy`: kotlin.String?, `sigHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_post_account_create(
        FfiConverterString.lower(`baseUrl`),FfiConverterString.lower(`account`),FfiConverterString.lower(`keysJson`),FfiConverterOptionalString.lower(`fundedBy`),FfiConverterString.lower(`sigHex`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `postCoverageReport`(`baseUrl`: kotlin.String, `reporter`: kotlin.String, `lat`: kotlin.Double, `lon`: kotlin.Double, `signalDbm`: kotlin.Int?, `carrierMccMnc`: kotlin.String, `technology`: kotlin.String, `dataHash`: kotlin.String, `sigHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_post_coverage_report(
        FfiConverterString.lower(`baseUrl`),FfiConverterString.lower(`reporter`),FfiConverterDouble.lower(`lat`),FfiConverterDouble.lower(`lon`),FfiConverterOptionalInt.lower(`signalDbm`),FfiConverterString.lower(`carrierMccMnc`),FfiConverterString.lower(`technology`),FfiConverterString.lower(`dataHash`),FfiConverterString.lower(`sigHex`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `postInferenceBid`(`baseUrl`: kotlin.String, `jobId`: kotlin.String, `bidder`: kotlin.String, `fee`: kotlin.ULong, `role`: kotlin.String, `nonce`: kotlin.ULong, `sigHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_post_inference_bid(
        FfiConverterString.lower(`baseUrl`),FfiConverterString.lower(`jobId`),FfiConverterString.lower(`bidder`),FfiConverterULong.lower(`fee`),FfiConverterString.lower(`role`),FfiConverterULong.lower(`nonce`),FfiConverterString.lower(`sigHex`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `postInferenceComplete`(`baseUrl`: kotlin.String, `jobId`: kotlin.String, `worker`: kotlin.String, `resultHash`: kotlin.String, `latencyMs`: kotlin.ULong, `outputText`: kotlin.String, `sigHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_post_inference_complete(
        FfiConverterString.lower(`baseUrl`),FfiConverterString.lower(`jobId`),FfiConverterString.lower(`worker`),FfiConverterString.lower(`resultHash`),FfiConverterULong.lower(`latencyMs`),FfiConverterString.lower(`outputText`),FfiConverterString.lower(`sigHex`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `postNodeCapability`(`baseUrl`: kotlin.String, `account`: kotlin.String, `sigHex`: kotlin.String, `epoch`: kotlin.ULong, `vision`: kotlin.Boolean, `audio`: kotlin.Boolean, `codeExec`: kotlin.Boolean, `tier`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_post_node_capability(
        FfiConverterString.lower(`baseUrl`),FfiConverterString.lower(`account`),FfiConverterString.lower(`sigHex`),FfiConverterULong.lower(`epoch`),FfiConverterBoolean.lower(`vision`),FfiConverterBoolean.lower(`audio`),FfiConverterBoolean.lower(`codeExec`),FfiConverterString.lower(`tier`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `postSensorCommit`(`baseUrl`: kotlin.String, `sensorId`: kotlin.String, `owner`: kotlin.String, `batchHash`: kotlin.String, `readingCount`: kotlin.ULong, `sensorType`: kotlin.String, `value`: kotlin.Double?, `sigHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_post_sensor_commit(
        FfiConverterString.lower(`baseUrl`),FfiConverterString.lower(`sensorId`),FfiConverterString.lower(`owner`),FfiConverterString.lower(`batchHash`),FfiConverterULong.lower(`readingCount`),FfiConverterString.lower(`sensorType`),FfiConverterOptionalDouble.lower(`value`),FfiConverterString.lower(`sigHex`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `postSensorRegister`(`baseUrl`: kotlin.String, `sensorId`: kotlin.String, `owner`: kotlin.String, `sensorType`: kotlin.String, `location`: kotlin.String?, `sigHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_post_sensor_register(
        FfiConverterString.lower(`baseUrl`),FfiConverterString.lower(`sensorId`),FfiConverterString.lower(`owner`),FfiConverterString.lower(`sensorType`),FfiConverterOptionalString.lower(`location`),FfiConverterString.lower(`sigHex`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `postStake`(`baseUrl`: kotlin.String, `account`: kotlin.String, `amount`: kotlin.ULong, `nonce`: kotlin.ULong, `signedBy`: kotlin.String, `sigHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_post_stake(
        FfiConverterString.lower(`baseUrl`),FfiConverterString.lower(`account`),FfiConverterULong.lower(`amount`),FfiConverterULong.lower(`nonce`),FfiConverterString.lower(`signedBy`),FfiConverterString.lower(`sigHex`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `postTransfer`(`baseUrl`: kotlin.String, `from`: kotlin.String, `to`: kotlin.String, `amount`: kotlin.ULong, `token`: kotlin.String, `memo`: kotlin.String?, `signedBy`: kotlin.String, `nonce`: kotlin.ULong, `sigHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_post_transfer(
        FfiConverterString.lower(`baseUrl`),FfiConverterString.lower(`from`),FfiConverterString.lower(`to`),FfiConverterULong.lower(`amount`),FfiConverterString.lower(`token`),FfiConverterOptionalString.lower(`memo`),FfiConverterString.lower(`signedBy`),FfiConverterULong.lower(`nonce`),FfiConverterString.lower(`sigHex`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `postUnstake`(`baseUrl`: kotlin.String, `account`: kotlin.String, `amount`: kotlin.ULong, `nonce`: kotlin.ULong, `signedBy`: kotlin.String, `sigHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_post_unstake(
        FfiConverterString.lower(`baseUrl`),FfiConverterString.lower(`account`),FfiConverterULong.lower(`amount`),FfiConverterULong.lower(`nonce`),FfiConverterString.lower(`signedBy`),FfiConverterString.lower(`sigHex`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `signAccountCreate`(`mnemonicWords`: kotlin.String, `chainId`: kotlin.String, `account`: kotlin.String, `keysJson`: kotlin.String, `fundedBy`: kotlin.String?): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_sign_account_create(
        FfiConverterString.lower(`mnemonicWords`),FfiConverterString.lower(`chainId`),FfiConverterString.lower(`account`),FfiConverterString.lower(`keysJson`),FfiConverterOptionalString.lower(`fundedBy`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `signCoverageReport`(`mnemonicWords`: kotlin.String, `chainId`: kotlin.String, `reporter`: kotlin.String, `lat`: kotlin.Double, `lon`: kotlin.Double, `carrierMccMnc`: kotlin.String, `dataHash`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_sign_coverage_report(
        FfiConverterString.lower(`mnemonicWords`),FfiConverterString.lower(`chainId`),FfiConverterString.lower(`reporter`),FfiConverterDouble.lower(`lat`),FfiConverterDouble.lower(`lon`),FfiConverterString.lower(`carrierMccMnc`),FfiConverterString.lower(`dataHash`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `signInferenceBid`(`mnemonicWords`: kotlin.String, `chainId`: kotlin.String, `bidder`: kotlin.String, `jobId`: kotlin.String, `fee`: kotlin.ULong, `role`: kotlin.String, `nonce`: kotlin.ULong): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_sign_inference_bid(
        FfiConverterString.lower(`mnemonicWords`),FfiConverterString.lower(`chainId`),FfiConverterString.lower(`bidder`),FfiConverterString.lower(`jobId`),FfiConverterULong.lower(`fee`),FfiConverterString.lower(`role`),FfiConverterULong.lower(`nonce`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `signInferenceComplete`(`mnemonicWords`: kotlin.String, `chainId`: kotlin.String, `worker`: kotlin.String, `jobId`: kotlin.String, `resultHash`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_sign_inference_complete(
        FfiConverterString.lower(`mnemonicWords`),FfiConverterString.lower(`chainId`),FfiConverterString.lower(`worker`),FfiConverterString.lower(`jobId`),FfiConverterString.lower(`resultHash`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `signNodeCapability`(`mnemonicWords`: kotlin.String, `account`: kotlin.String, `epoch`: kotlin.ULong): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_sign_node_capability(
        FfiConverterString.lower(`mnemonicWords`),FfiConverterString.lower(`account`),FfiConverterULong.lower(`epoch`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `signSensorCommit`(`mnemonicWords`: kotlin.String, `chainId`: kotlin.String, `sensorId`: kotlin.String, `owner`: kotlin.String, `batchHash`: kotlin.String, `readingCount`: kotlin.ULong): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_sign_sensor_commit(
        FfiConverterString.lower(`mnemonicWords`),FfiConverterString.lower(`chainId`),FfiConverterString.lower(`sensorId`),FfiConverterString.lower(`owner`),FfiConverterString.lower(`batchHash`),FfiConverterULong.lower(`readingCount`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `signStake`(`mnemonicWords`: kotlin.String, `chainId`: kotlin.String, `account`: kotlin.String, `amount`: kotlin.ULong, `nonce`: kotlin.ULong): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_sign_stake(
        FfiConverterString.lower(`mnemonicWords`),FfiConverterString.lower(`chainId`),FfiConverterString.lower(`account`),FfiConverterULong.lower(`amount`),FfiConverterULong.lower(`nonce`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `signTransfer`(`mnemonicWords`: kotlin.String, `chainId`: kotlin.String, `fromAccount`: kotlin.String, `toAccount`: kotlin.String, `amount`: kotlin.ULong, `token`: kotlin.String, `nonce`: kotlin.ULong): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_sign_transfer(
        FfiConverterString.lower(`mnemonicWords`),FfiConverterString.lower(`chainId`),FfiConverterString.lower(`fromAccount`),FfiConverterString.lower(`toAccount`),FfiConverterULong.lower(`amount`),FfiConverterString.lower(`token`),FfiConverterULong.lower(`nonce`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `signUnstake`(`mnemonicWords`: kotlin.String, `chainId`: kotlin.String, `account`: kotlin.String, `amount`: kotlin.ULong, `nonce`: kotlin.ULong): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_sign_unstake(
        FfiConverterString.lower(`mnemonicWords`),FfiConverterString.lower(`chainId`),FfiConverterString.lower(`account`),FfiConverterULong.lower(`amount`),FfiConverterULong.lower(`nonce`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `signWithRole`(`mnemonicWords`: kotlin.String, `chainId`: kotlin.String, `roleIndex`: kotlin.UInt, `canonicalJson`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_sign_with_role(
        FfiConverterString.lower(`mnemonicWords`),FfiConverterString.lower(`chainId`),FfiConverterUInt.lower(`roleIndex`),FfiConverterString.lower(`canonicalJson`),_status)
}
    )
    }
    

    @Throws(MobileCoreException::class) fun `verifyBleFrameSig`(`rawFrame`: kotlin.ByteArray, `flipperPubkeyHex`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCallWithError(MobileCoreException) { _status ->
    UniffiLib.INSTANCE.uniffi_btcpc_mobile_core_fn_func_verify_ble_frame_sig(
        FfiConverterByteArray.lower(`rawFrame`),FfiConverterString.lower(`flipperPubkeyHex`),_status)
}
    )
    }
    


